print("        _            _            _             _                    _              _      _                  _          ")
print("       / /\         /\ \         /\ \     _    / /\                 /\ \           /\ \   /\_\               /\ \     _  ")
print("      / /  \       /  \ \       /  \ \   /\_\ / /  \                \ \ \         /  \ \ / / /         _    /  \ \   /\_\
")
print("     / / /\ \__   / /\ \ \     / /\ \ \_/ / // / /\ \               /\ \_\       / /\ \ \\ \ \__      /\_\ / /\ \ \_/ / /")
print("    / / /\ \___\ / / /\ \_\   / / /\ \___/ // / /\ \ \             / /\/_/      / / /\ \_\\ \___\    / / // / /\ \___/ / ")
print("    \ \ \ \/___// /_/_ \/_/  / / /  \/____// / /  \ \ \           / / /        / / /_/ / / \__  /   / / // / /  \/____/ ")
print("     \ \ \     / /____/\    / / /    / / // / /___/ /\ \         / / /        / / /__\/ /  / / /   / / // / /    / / /")
print(" _    \ \ \   / /\____\/   / / /    / / // / /_____/ /\ \       / / /        / / /_____/  / / /   / / // / /    / / / ")
print("/_/\__/ / /  / / /______  / / /    / / // /_________/\ \ \  ___/ / /__      / / /\ \ \   / / /___/ / // / /    / / /  ")
print("\ \/___/ /  / / /_______\/ / /    / / // / /_       __\ \_\/\__\/_/___\    / / /  \ \ \ / / /____\/ // / /    / / /  ")
print(" \_____\/   \/__________/\/_/     \/_/ \_\___\     /____/_/\/_________/    \/_/    \_\/ \/_________/ \/_/     \/_/   ")
print("")
print("")
print("")
print("Quer ir pra aula?")
print("[1] Sim")
print("[2] Não")
vontade= int(100)
op0 = int(input())
while (op0 < 1) or (op0 > 2):
    print("[1] Sim")
    print("[2] Não")
    op0 = int(input())
if op0 == 1:
    if vontade > 0:
        nome = input("Qual o nome do seu personagem ")
        print("")
        print("ESTÁ CHOVENDO LÁ FORA E VOCÊ PRECISA CHEGAR NO SENAI PARA SUA AULA")
        print("")
        print("[VONTADE DE IR PRA AULA: 100%]")
        print("Você deseja colocar um casaco? ")
        print("[1] Sim")
        print("[2] Não")
        op1 = int(input())
        while (op1 < 1) or (op1 > 2):
            print("[1] Sim")
            print("[2] Não")
            op1 = int(input())
        print("")
        print("Sua mochila é pequena, você pode optar por levar: ")
        print("[1] Guarda chuva")
        print("[2] Capa de chuva")
        print("[3] Ir no louco (não levar nada)")
        op2 = int(input())
        while (op2 < 1) or (op2 > 3):
            print("[1] Guarda chuva")
            print("[2] Capa de chuva")
            print("[3] Ir no louco (não levar nada)")
            if op1 == 2:
                vontade = vontade - 15
            op2 = int(input())
        print("")
    if vontade > 0:
        print("Você saiu e encontrou-se com um cachorro raivoso pronto para te atacar, você quer: ")
        print("[1] Defender-se")
        print("[2] Correr")
        if op1 == 2:
            vontade = vontade - 15
        op3 = int(input())
        while (op3 < 1) or (op3 > 2):
            print("[1] Defender-se")
            print("[2] Correr")
            op3 = int(input())
        if op3 == 1 and op2 == 1:
            print("Você usou o guarda-chuva e ele fugiu!")
            vontade = vontade - 15
            print("[VONTADE DE IR PRA AULA: {}%]".format(vontade))
        elif op3 == 1 and op2 != 1:
            print("Você voltou pra casa machucado e não pôde ir pra aula  {}".format(nome))
            print("[VONTADE DE IR PRA AULA: 0%]")
            print("")
            print("         _        _         _   _       ")
            print("        /\ \     /\ \      /\_\/\_\ _   ")
            print("       /  \ \    \ \ \    / / / / //\_\ ")
            print("      / /\ \ \   /\ \_\  /\ \/ \ \/ / / ")
            print("     / / /\ \_\ / /\/_/ /  \____\__/ /  ")
            print("    / /_/_ \/_// / /   / /\/________/  ")
            print("   / /____/\  / / /   / / /\/_// / /   ")
            print("  / /\____\/ / / /   / / /    / / /   ")
            print(" / / /   ___/ / /__ / / /    / / /   ")
            print("/ / /   /\__\/_/___\\/_/    / / /    ")
            print("\/_/    \/_________/        \/_/     ")
            exit()
        else:
            print("Você correu bastante e conseguiu despistar o cachorro raivoso")
            vontade = vontade - 20

    if vontade > 0: 
        print("")           
        print("[VONTADE DE IR PRA AULA: {}%]".format(vontade))
        print("Você avistou dois caminhos, um deles tem uma poça de lama")
        print("Você deseja ir pela esquerda ou pela direita")
        print("[1] Esquerda")
        print("[2] Direita")
        if op1 == 2:
            vontade = vontade - 15
        op4 = int(input())
        while (op4 < 1) or (op4 > 2):
            print("[1] Esquerda")
            print("[2] Direita")
            op4 = int(input())
        print("Ops!! Os dois caminhos davam na lama")
        if op2 == 2:
            print("Por você ter pego a capa, você não se sujou")
            vontade = vontade - 10
        else:
            print("Por você não ter pego a capa, você se sujou")
            vontade = vontade - 30  
    if vontade > 0:
        print("")
        print("[VONTADE DE IR PRA AULA: {}%]".format(vontade))
        print("Você está numa avenida movimentada")
        print("Você está atrasado")
        print("Mas você deparou-se com um atalho calmo, você escolhe: ")
        print("[1] Atalho calmo")
        print("[2] Avenida")
        if op1 == 2:
            vontade = vontade - 15
        op5 = int(input())
        while (op5 < 1) or (op5 > 2):
            print("[1] Atalho calmo")
            print("[2] Avenida")
            op5 = int(input())
        if op5==1:
            print("Parecia um lugar calmo mas um bandido te esperava. e te levou tudo")
            print("Você ficou só com a roupa do corpo e teve que voltar para casa  {}".format(nome))
            print("[VONTADE DE IR PRA AULA: 0%]")
            print("")
            print("         _        _         _   _       ")
            print("        /\ \     /\ \      /\_\/\_\ _   ")
            print("       /  \ \    \ \ \    / / / / //\_\ ")
            print("      / /\ \ \   /\ \_\  /\ \/ \ \/ / / ")
            print("     / / /\ \_\ / /\/_/ /  \____\__/ /  ")
            print("    / /_/_ \/_// / /   / /\/________/  ")
            print("   / /____/\  / / /   / / /\/_// / /   ")
            print("  / /\____\/ / / /   / / /    / / /   ")
            print(" / / /   ___/ / /__ / / /    / / /   ")
            print("/ / /   /\__\/_/___\\/_/    / / /    ")
            print("\/_/    \/_________/        \/_/     ")
            exit()
        else:
            print("Você resbalou no meio-fio enquanto atravessava a avenida e caiu na calçada")
            vontade = vontade - 15
        print("")
    if vontade > 0:
        print("Mas você conseguiu continuar com seu trajeto")
        print("")
        print("VOCÊ CHEGOU NO SENAI")
        print("[VONTADE DE IR PRA AULA: {}%]".format(vontade))
        print("")
        print("Você chega na sala marcada, porém, ela está vazia")
        print("Você deseja: ")
        print("[1] Entrar na sala mesmo assim")
        print("[2] Esperar o professor")
        op6 = int(input())
        while (op6 < 1) or (op6 > 2):
            print("[1] Entrar na sala mesmo assim")
            print("[2] Esperar o professor")
            op6 = int(input())
            print("")
        if op6==1:
            print("Você não poderia entrar na sala naquela hora")
            print("Você acaba sendo EXPULSO do SENAI")
        else:
            print("A aula não era naquela sala")
            print("Você se dirige para a correta para ter a sua aula")
            print("PARABÉNS VOCÊ CONSEGUIU {}!!".format(nome))
            print("")
            print("         _        _         _   _       ")
            print("        /\ \     /\ \      /\_\/\_\ _   ")
            print("       /  \ \    \ \ \    / / / / //\_\ ")
            print("      / /\ \ \   /\ \_\  /\ \/ \ \/ / / ")
            print("     / / /\ \_\ / /\/_/ /  \____\__/ /  ")
            print("    / /_/_ \/_// / /   / /\/________/  ")
            print("   / /____/\  / / /   / / /\/_// / /   ")
            print("  / /\____\/ / / /   / / /    / / /   ")
            print(" / / /   ___/ / /__ / / /    / / /   ")
            print("/ / /   /\__\/_/___\\/_/    / / /    ")
            print("\/_/    \/_________/        \/_/     ")
    else:
        print("SUA VONTADE DE IR PARA A AULA SE ESGOTOU {}".format(nome))
        print("[VONTADE DE IR PRA AULA: 0%]")
        print("")
        print("         _        _         _   _       ")
        print("        /\ \     /\ \      /\_\/\_\ _   ")
        print("       /  \ \    \ \ \    / / / / //\_\ ")
        print("      / /\ \ \   /\ \_\  /\ \/ \ \/ / / ")
        print("     / / /\ \_\ / /\/_/ /  \____\__/ /  ")
        print("    / /_/_ \/_// / /   / /\/________/  ")
        print("   / /____/\  / / /   / / /\/_// / /   ")
        print("  / /\____\/ / / /   / / /    / / /   ")
        print(" / / /   ___/ / /__ / / /    / / /   ")
        print("/ / /   /\__\/_/___\\/_/    / / /    ")
        print("\/_/    \/_________/        \/_/     ")
else:
    print("")
    print("         _        _         _   _       ")
    print("        /\ \     /\ \      /\_\/\_\ _   ")
    print("       /  \ \    \ \ \    / / / / //\_\ ")
    print("      / /\ \ \   /\ \_\  /\ \/ \ \/ / / ")
    print("     / / /\ \_\ / /\/_/ /  \____\__/ /  ")
    print("    / /_/_ \/_// / /   / /\/________/  ")
    print("   / /____/\  / / /   / / /\/_// / /   ")
    print("  / /\____\/ / / /   / / /    / / /   ")
    print(" / / /   ___/ / /__ / / /    / / /   ")
    print("/ / /   /\__\/_/___\\/_/    / / /    ")
    print("\/_/    \/_________/        \/_/     ")